#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# tools/seal-binary-closure.sh — emit seal directives for a binary AND its
# dynamic-link closure (its ldd shared libraries + the dynamic loader).
#
# WHY: sealing only the binary (e.g. `seal /usr/sbin/sshd full`) leaves the
# shared objects it loads writable — tampering a .so reported by
# `ldd /usr/sbin/sshd` is as good as tampering the binary. Full tamper-proofing
# of even one executable pulls in its whole lib closure. (Those libs live under
# /usr/lib, which is exactly why a recursive `seal /usr` is impractical — see
# LIMITATIONS.md "not a whole-system read-only tool".)
#
# Seals key on INODE: every emitted path is resolved to its real target
# (readlink -f), because the loader refuses a symlink leaf and a version symlink
# (libfoo.so -> libfoo.so.1.2.3) must be sealed at the real file. Re-run this
# after package upgrades — upgrades replace files with new inodes, so the old
# seals would no longer match.
#
# Usage:
#   tools/seal-binary-closure.sh /usr/sbin/sshd [FLAGS]    # FLAGS default: full
#   tools/seal-binary-closure.sh sshd                      # resolved via PATH
# Output: seal directives on stdout (pipe/append into a profile, then review).
set -eu

[ "$#" -ge 1 ] || { echo "usage: $0 BINARY [FLAGS]" >&2; exit 2; }
arg=$1
flags=${2:-full}

# Resolve the binary: accept a path or a PATH-resolvable command name.
if [ -e "$arg" ]; then bin=$arg; else bin=$(command -v "$arg" 2>/dev/null || true); fi
[ -n "${bin:-}" ] && [ -e "$bin" ] || { echo "error: cannot find binary '$arg'" >&2; exit 1; }
bin=$(readlink -f "$bin")
[ -f "$bin" ] || { echo "error: '$bin' is not a regular file" >&2; exit 1; }

emit() {  # emit one seal line for a real-file path, deduped
	real=$(readlink -f "$1" 2>/dev/null || true)
	[ -n "$real" ] && [ -f "$real" ] || return 0
	case " $SEEN " in *" $real "*) return 0 ;; esac
	SEEN="$SEEN $real"
	printf 'seal %s %s\n' "$real" "$flags"
}
SEEN=""

printf '# dynamic-link closure for %s (flags=%s) — generated by seal-binary-closure.sh\n' "$bin" "$flags"
printf '# re-run after upgrades: replaced files get new inodes and these seals stop matching.\n'
emit "$bin"

# ldd lines look like:
#   libfoo.so.1 => /usr/lib/x86_64-linux-gnu/libfoo.so.1 (0x00007f...)
#   /lib64/ld-linux-x86-64.so.2 (0x00007f...)
# Take the resolved path: the field after "=>", or the first field if no "=>".
# Read ldd output from a temp file (not a pipe) so emit()'s dedup state persists.
lddf=$(mktemp)
trap 'rm -f "$lddf"' EXIT INT TERM
if ldd "$bin" >"$lddf" 2>/dev/null; then
	while IFS= read -r line; do
		case "$line" in
			*"=>"*)
				p=$(printf '%s' "$line" | sed -n 's/.*=> *\([^ ]*\).*/\1/p') ;;
			*"/"*"("*)
				p=$(printf '%s' "$line" | sed -n 's/^[[:space:]]*\([/][^ ]*\).*/\1/p') ;;
			*) p="" ;;
		esac
		[ -n "$p" ] && [ -e "$p" ] && emit "$p"
	done < "$lddf"
else
	printf '# (note: ldd reported no dynamic dependencies — static binary?)\n' >&2
fi
