#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Re-generate profiles/all-daemons.conf from the per-daemon profiles.
# The parser supports only the `seal` directive (no include), so the
# aggregate is a static concatenation. Run after editing any
# per-daemon profile to keep the aggregate in sync.

set -eu

cd "$(dirname "$0")/.."

OUT=profiles/all-daemons.conf

# §D-19: auto-discover per-daemon profiles. The previous hardcoded
# ORDER=(sshd ...) array silently excluded any new profiles/*.conf
# from the aggregate; this listing picks up everything except the
# aggregate output itself.
mapfile -t PROFILES < <(
    find profiles -maxdepth 1 -name '*.conf' \
        ! -name 'all-daemons.conf' \
        -printf '%f\n' | sort
)

profile_count=${#PROFILES[@]}

{
    cat <<HEADER
# Aggregate profile — union of all per-daemon profiles in profiles/.
# Generated by concatenating the seal directives from each
# profiles/<daemon>.conf. The parser does not support an include
# directive (only 'seal'), so this static file is the production
# artifact for loading the full cocktail in one shot.
#
# Re-generate with: tests/build-all-daemons-conf.sh
# Smoke with:       sudo ./compartment-bpf --pin profiles/all-daemons.conf
#
# Manifest headers per daemon live in profiles/<daemon>.conf.
# Profiles included (${profile_count}): $(printf '%s ' "${PROFILES[@]%.conf}" | sed 's/ $//')

HEADER
    for f in "${PROFILES[@]}"; do
        d="${f%.conf}"
        printf '# === %s ===\n' "$d"
        # ED-1 (exec-domain): include `actor NAME = PATH ...` declarations
        # alongside `seal ` lines. Each per-daemon profile keeps actor
        # decls before the seal lines that reference them, so iterating
        # the file in source order preserves the parser's "declare
        # before use" rule. Pre-ED-1 builders dropped actor lines; that
        # silently broke the aggregate the moment aide.conf or
        # postgres.conf shipped an actor= clause (Leader-8 ED-13).
        grep -E '^(seal |actor )' "profiles/${f}" || true
        echo
    done
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"

seals=$(grep -c '^seal ' "$OUT")
printf 'wrote %s (%d seal directives)\n' "$OUT" "$seals"
