# SPDX-License-Identifier: Apache-2.0
# shellcheck shell=sh
# tests/lib-realbin.sh — resolve a REAL executable fixture (regular file, not
# a symlink) for suites that need "a binary to exec / seal / copy".
#
# Why this exists
# ---------------
# Test after test hard-coded /usr/bin/true or /bin/true as "a tiny binary that
# always exists". On Ubuntu 26.04 the default coreutils package is
# `coreutils-from-uutils`, where /usr/bin/true is a SYMLINK
# (/usr/bin/true -> gnutrue, /usr/bin/ls -> ../lib/cargo/bin/coreutils/ls).
# The loader refuses a symlink leaf by design:
#
#   actor stab_actor: refusing /usr/bin/true: symlink leaf (O_NOFOLLOW).
#   seal /usr/bin/true: refusing to seal a symlink leaf.
#
# so every one of those call sites silently degraded — in the stability
# harness the whole pin/unpin churn became a no-op that still reported PASS.
# Chasing the symlink with `readlink -f` is NOT the fix either: on uutils it
# lands on the shared multi-call binary, so sealing it would seal every
# coreutils applet on the box.
#
# The fix is to stop borrowing a system binary. realbin_noop / realbin_false
# build a 30-line static ELF into a cache directory and hand back its path.
# Only if no compiler is available do we fall back to probing system
# candidates, and then only ones that pass realbin_is_real_elf (regular file,
# not a symlink, ELF magic).
#
# Usage:
#   . "$REPO/tests/lib-realbin.sh"
#   BIN=$(realbin_noop)  || { echo "SKIP: no usable exec fixture"; exit 77; }
#   FALSE=$(realbin_false)
#
# Both helpers echo an absolute path on stdout and return 0, or return 1 with
# no output. They are idempotent and cache their build, so calling them in a
# loop costs one stat().
#
# REALBIN_CACHE overrides the cache directory (default /tmp/compartment-realbin).

: "${REALBIN_CACHE:=/tmp/compartment-realbin}"

# realbin_is_real_elf PATH
#   0 if PATH is an executable REGULAR file that is not a symlink and starts
#   with the ELF magic. Anything else (symlink, script, missing) is refused.
realbin_is_real_elf() {
	_rb_p=$1
	[ -n "$_rb_p" ] || return 1
	# -L first: a symlink to a regular file also satisfies -f.
	[ -L "$_rb_p" ] && return 1
	[ -f "$_rb_p" ] || return 1
	[ -x "$_rb_p" ] || return 1
	# ELF magic 0x7f 'E' 'L' 'F'. od is in coreutils on every distro we
	# target, including uutils.
	_rb_magic=$(od -An -tx1 -N4 "$_rb_p" 2>/dev/null | tr -d ' \n')
	[ "$_rb_magic" = "7f454c46" ]
}

# _realbin_build <cache-name> <return-code>
#   Compile a minimal `int main(void){return N;}` into $REALBIN_CACHE/<name>.
#   Static if the toolchain can, dynamic otherwise (either way it is a real
#   regular ELF file, which is all the callers need). Echoes the path.
_realbin_build() {
	_rb_name=$1
	_rb_rc=$2
	_rb_out="$REALBIN_CACHE/$_rb_name"

	if realbin_is_real_elf "$_rb_out"; then
		printf '%s\n' "$_rb_out"
		return 0
	fi

	command -v cc >/dev/null 2>&1 || command -v gcc >/dev/null 2>&1 || return 1
	_rb_cc=$(command -v cc 2>/dev/null || command -v gcc 2>/dev/null)

	mkdir -p "$REALBIN_CACHE" 2>/dev/null || return 1
	_rb_src="$REALBIN_CACHE/.$_rb_name.c"
	cat >"$_rb_src" <<REALBIN_SRC
/* generated by tests/lib-realbin.sh — a real regular-file ELF fixture,
 * deliberately NOT /usr/bin/true (a symlink under uutils coreutils). */
int main(void) { return $_rb_rc; }
REALBIN_SRC

	# Static preferred: strict-launch style checks and actor-identity
	# checks are happiest with a self-contained binary, and a static file
	# has no interpreter symlink of its own.
	if ! "$_rb_cc" -O2 -static -o "$_rb_out.tmp$$" "$_rb_src" 2>/dev/null; then
		if ! "$_rb_cc" -O2 -o "$_rb_out.tmp$$" "$_rb_src" 2>/dev/null; then
			rm -f "$_rb_src" "$_rb_out.tmp$$"
			return 1
		fi
	fi
	chmod 0755 "$_rb_out.tmp$$" 2>/dev/null || true
	mv -f "$_rb_out.tmp$$" "$_rb_out" 2>/dev/null || {
		rm -f "$_rb_out.tmp$$"
		return 1
	}
	rm -f "$_rb_src"

	realbin_is_real_elf "$_rb_out" || return 1
	printf '%s\n' "$_rb_out"
}

# _realbin_fallback <candidate...>
#   First candidate that passes realbin_is_real_elf. Used only when there is
#   no compiler on the box.
_realbin_fallback() {
	for _rb_c in "$@"; do
		if realbin_is_real_elf "$_rb_c"; then
			printf '%s\n' "$_rb_c"
			return 0
		fi
	done
	return 1
}

# realbin_noop  — path to a real ELF that exits 0.
realbin_noop() {
	_realbin_build realbin-noop 0 && return 0
	_realbin_fallback /usr/bin/true /bin/true /usr/bin/cat /bin/cat
}

# realbin_false — path to a real ELF that exits 1. Distinct inode from
# realbin_noop, which matters for actor-identity tests.
realbin_false() {
	_realbin_build realbin-false 1 && return 0
	_realbin_fallback /usr/bin/false /bin/false
}
