#!/usr/bin/env bash
# Copyright (c) 2026 Nenad Mićić <nenad@micic.be>
# SPDX-License-Identifier: Apache-2.0
#
# ═══════════════════════════════════════════════════════════════════════
# TIMESTAMP & ARCHIVE SCRIPT
# ═══════════════════════════════════════════════════════════════════════
#
# PURPOSE:
#   Create a cryptographic proof-of-existence for a release.
#   SHA256 checksums of all source files + OpenTimestamps blockchain anchor.
#
# WHAT IT DOES:
#   1. Generates SHA256 checksums of all project files
#   2. Creates a root hash of the checksums file
#   3. Submits root hash to OpenTimestamps (Bitcoin blockchain anchor)
#   4. Creates a git archive branch with the proof artifacts
#
# USAGE:
#   ./scripts/timestamp.sh              # Generate checksums + OTS proof
#   ./scripts/timestamp.sh v1.1.0       # Also create archive/v1.1.0 branch
#
# PREREQUISITES:
#   - ots (opentimestamps-client): pipx install opentimestamps-client
#   - git (for archive branch creation)
#
# VERIFICATION (anyone can verify later):
#   git checkout archive/v1.1.0
#   ots verify archive/SHA256SUMS.root.ots
#   sha256sum -c archive/SHA256SUMS
#
# HOW TO REDO (if you need to re-timestamp a version):
#   1. Check out the exact commit: git checkout v1.1.0
#   2. Run: ./scripts/timestamp.sh v1.1.0
#   3. This overwrites the archive branch with fresh proofs
#
# FULL RELEASE WORKFLOW:
#   1. Ensure all tests pass
#   2. Tag the release:
#        git tag -a v1.1.0 -m "v1.1.0"
#        git push origin v1.1.0
#   3. Run this script with the version:
#        ./scripts/timestamp.sh v1.1.0
#   4. Done — archive branch has the proof, main stays clean
#
# FILE LAYOUT:
#   archive/                     <- gitignored on main, tracked on archive branch
#   ├── SHA256SUMS               <- checksums of all source files
#   ├── SHA256SUMS.root          <- hash of the checksums file itself
#   └── SHA256SUMS.root.ots      <- OpenTimestamps proof (blockchain anchor)
#
# ═══════════════════════════════════════════════════════════════════════

set -euo pipefail

VERSION="${1:-}"
ARCHIVE_DIR="archive"
SUMS="$ARCHIVE_DIR/SHA256SUMS"
ROOT="$ARCHIVE_DIR/SHA256SUMS.root"

# ── Pre-flight: refuse to run with uncommitted changes ──────────────────
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "ERROR: uncommitted changes present. Stash or commit first." >&2
  exit 1
fi

# ── Resolve ots binary ──────────────────────────────────────────────────
OTS="$(command -v ots 2>/dev/null || echo "$HOME/.local/bin/ots")"

mkdir -p "$ARCHIVE_DIR"

# ── Step 1: Generate checksums ──────────────────────────────────────────
rm -f "$SUMS" "$ROOT" "$ROOT.ots"

echo "Generating SHA256 checksums..."
find . -type f \
  ! -path "./.git/*" \
  ! -path "./.claude/*" \
  ! -path "./archive/*" \
  ! -path "./node_modules/*" \
  ! -name ".DS_Store" \
  -print0 \
| sort -z \
| xargs -0 sha256sum > "$SUMS"

FILE_COUNT=$(wc -l < "$SUMS")
echo "SHA256 hashes written to $SUMS ($FILE_COUNT files)"
echo ""

# ── Step 2: Root hash ───────────────────────────────────────────────────
sha256sum "$SUMS" > "$ROOT"
echo "Root hash: $(cat "$ROOT")"
echo ""

# ── Step 3: OpenTimestamps ──────────────────────────────────────────────
if [ -x "$OTS" ]; then
  "$OTS" stamp "$ROOT"
  echo "OpenTimestamps proof: $ROOT.ots"
else
  echo "NOTE: ots not found — skipping OpenTimestamps stamp"
  echo "Install: pipx install opentimestamps-client"
fi

echo ""
echo "Archive artifacts in $ARCHIVE_DIR/"

# ── Step 4: Create archive branch (if version specified) ────────────────
if [ -n "$VERSION" ]; then
  BRANCH="archive/$VERSION"
  CURRENT=$(git branch --show-current)

  echo ""
  echo "Creating archive branch: $BRANCH"

  # Delete existing branch if present (for redo)
  git branch -D "$BRANCH" 2>/dev/null || true

  # Create orphan branch with archive artifacts
  git checkout --orphan "$BRANCH"
  git rm -rf --cached . >/dev/null 2>&1 || true
  git add -f "$ARCHIVE_DIR/"
  git commit -m "archive: $VERSION checksums and timestamp proof

Generated by scripts/timestamp.sh
Files checksummed: $FILE_COUNT
Root hash: $(cat "$ROOT")
Source tag: $VERSION"

  git push -u origin "$BRANCH" --force

  # Return to original branch
  git checkout -f "$CURRENT"

  echo ""
  echo "Done. Archive branch pushed: $BRANCH"
  echo ""
  echo "To verify:"
  echo "  git checkout $BRANCH"
  echo "  sha256sum -c $SUMS"
  [ -f "$ROOT.ots" ] && echo "  ots verify $ROOT.ots"
else
  echo ""
  echo "To create an archive branch, run with a version:"
  echo "  ./scripts/timestamp.sh v1.1.0"
fi
